[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5.2", features = ["api-all", "macos-private-api"] }
window-vibrancy = "0.3.0"
lofty = { version = "0.17.1" }
base64 = "0.13.0"
tauri-plugin-fs-watch = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
filetime = "0.2.22"
chksum-md5 = "0.0.0"
rayon = "1.8.0"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
scraper = "0.12"
http = "1.0.0"
http-range = "0.1.5"
tauri-utils = "1.5.2"
percent-encoding = "2.3.1"
symphonia = { version = "0.5.4", features = ["mp3", "flac", "opt-simd"] }
webrtc = "0.9.0"
log = "0.4.20"
bytes = "1.5.0"
tokio-util = "0.7.10"
ringbuffer = "0.15.0"
atomic-wait = "1.1.0"
cpal = "0.15.3"
rb = "0.4.1"
rubato = "0.15.0"
arrayvec = "0.7.4"
env_logger = "0.11.3"
rustfft = "6.2.0"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
